spring.application.name=proyecto

logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

spring.datasource.url=jdbc:oracle:thin:@d3cf94t30ofl9h1z_tp?TNS_ADMIN=${user.dir}/Wallet_D3CF94T30OFL9H1Z
spring.datasource.username=BDPELICULAS
spring.datasource.password=DuocUC2026DB
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
